### ISSUE TITLE
createBlacklist lib error

### ISSUE THREAD

**Issue by FriiZoLoGYy** [t6c/sellapp-api-wrapper#2]
When creating a Blacklist you will always get `type.toUpperCase is not a function`

**Comment by t6c** [comment]
> When creating a Blacklist you will always get `type.toUpperCase is not a function`

Hi i just checked the code and tested the package, everything still functions as normal.
Please keep in mind that blacklist types (IP, EMAIL, COUNTRY) must be a string, you can see [the detailed example here](https://github.com/t6c/sellapp-api-wrapper#endpoints-examples-of-usage)


If that still doesn't solve the problem, feel free to shoot me a DM on Discord, i'll see if i can help ya: **time#3167**

**Comment by FriiZoLoGYy** [comment]
After fresh eyes I realized my error
